services:
  - type: web
    name: car-match
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn CarMatch.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: carmatch-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "car-match.onrender.com"
    staticPublishPath: staticfiles 